apiVersion: v1
kind: Pod
metadata:
  name: rainfall
  labels:
    app: rainfall
spec:
  containers:
    - image: localhost:5000/rainfall:1.0.2
      name: rainfall
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      volumeMounts:
        - name: config-vol
          mountPath: /rainfall/config
  volumes:
    - name: config-vol
      configMap:
        name: rainfall-config