apiVersion: v1
kind: Service
metadata:
  name: rainfall-svc
spec:
  ports:
    - name: 'rainfall'
      targetPort: 8080
      port: 8080
      nodePort: 30123
      protocol: TCP
  selector:
    app: rainfall
  type: NodePort